name: bl_inshort
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_riverpod: ^3.0.3
  path: ^1.9.1
  go_router: ^17.0.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.2.2
  dio: ^5.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/network/mock/responses/feed_mock.json
    - lib/core/network/mock/responses/notification_mock.json
